MvcProjectCamp/Controllers/AuthorizationController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjectCamp.Controllers
{
    public class AuthorizationController : Controller
    {
        // GET: Authorization
        AdminManager adm = new AdminManager(new EfAdminDal());
        public ActionResult Index()
        {
            var values = adm.GetList();
            return View(values);
        }

        [HttpGet]
        public ActionResult AddAdmin()
        {
            List<SelectListItem> valuesYetki = (from x in adm.GetList()
                                                select new SelectListItem
                                                {
                                                    Text = x.AdminRole,
                                                    Value = x.AdminID.ToString()
                                                }).ToList();
            ViewBag.vly = valuesYetki;
            return View();
        }

        [HttpPost]
        public ActionResult AddAdmin(Admin p)
        {
            adm.AdminAddBL(p);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult EditAdmin(int id)
        {
            List<SelectListItem> valuesYetki = (from x in adm.GetList()
                                                select new SelectListItem
                                                {
                                                    Text = x.AdminRole,
                                                    Value = x.AdminID.ToString()
                                                }).ToList();
            ViewBag.vly = valuesYetki;
            var value = adm.GetByIDBL(id);
            return View(value);
        }

        [HttpPost]
        public ActionResult EditAdmin(Admin admin)
        {
            adm.AdminUpdateBL(admin);
            return RedirectToAction("Index");
        }
    }
}

MvcProjectCamp/Views/Authorization/AddAdmin.cshtml
@model EntityLayer.Concrete.Admin
@{
    ViewBag.Title = "AddAdmin";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@using (Html.BeginForm("AddAdmin", "Authorization", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Admin Kullanıcı Adı :")
        @Html.TextBoxFor(x => x.AdminUserName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.AdminUserName)
        <br />
        @Html.Label("Şifreyi Giriniz :")
        @Html.TextBoxFor(x => x.AdminPassword, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.AdminPassword)
        <br />
        @Html.Label("Admin Rolü Seçiniz :")
        @Html.DropDownListFor(x => x.AdminID, (List<SelectListItem>)ViewBag.vly, new { @class = "form-control" })
        <br /> <br />
        <button class="btn btn-info">Kaydet</button>
    </div>
}

MvcProjectCamp/Views/Authorization/EditAdmin.cshtml
@model EntityLayer.Concrete.Admin
@{
    ViewBag.Title = "EditAdmin";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("EditAdmin", "Authorization", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.AdminID, new { @class = "form-control" })

        @Html.Label("Admin Kullanıcı Adı :")
        @Html.TextBoxFor(x => x.AdminUserName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.AdminUserName)
        <br />
        @Html.Label("Şifreyi Giriniz :")
        @Html.TextBoxFor(x => x.AdminPassword, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.AdminPassword)
        <br />
        @Html.Label("Admin Rolü Seçiniz :")
        @Html.DropDownListFor(x => x.AdminID, (List<SelectListItem>)ViewBag.vly, new { @class = "form-control" })
        <br />
        @Html.Label("Admin Aktiflik Seçiniz :")
        @Html.CheckBoxFor(x => x.AdminStatus)
        <br /> <br />
        <button class="btn btn-info">Kaydet</button>
    </div>
}

MvcProjectCamp/Views/Authorization/Index.cshtml
@using EntityLayer.Concrete
@model List<Admin>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@{
    string color = "";
    string durum = "";
}

<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Kullanıcı Adı</th>
        <th>Yetki</th>
        <th>Durum</th>
        <th>Pasif Yap</th>
        <th>Düzenleme</th>
    </tr>
    @foreach (var item in Model)
    {
        if (item.AdminStatus)
        {
            color = "badge badge-success";
            durum = "Aktif";
        }
        else
        {
            color = "badge badge-danger";
            durum = "Pasif";
        }
        <tr>
            <th>@item.AdminID</th>
            <td>@item.AdminUserName</td>
            <td>@item.AdminRole</td>
            <td class="project-state">
                <span class="@color">@durum</span>
            </td>
            <td><a href="/Authorization/DeleteCategory/@item.AdminID" class="btn btn-danger">Pasif Yap</a></td>
            <td><a href="/Authorization/EditAdmin/@item.AdminID" class="btn btn-warning">Düzenle</a></td>
        </tr>
    }
</table>
<br />
<a href="/Authorization/AddAdmin" class="btn btn-info">Yeni Admin Ekle</a>